### ISSUE TITLE
Args File Redundanz

### ISSUE THREAD

**Issue by TheSmartGerman** [Wolfgang-03/Open3E-HA#3]
Im args werden doppelte Informationen übergeben:

Wenn
`--config
devices.json
`
Verwendet wird muss das Device nicht mit übergeben werden, damit ist folgendes überflüssig:

`-dev vcal`

@Wolfgang-03 kannst du in deinem repository auch noch Diskussionen aktivieren? Dann könnte man allgemeine Themen dort diskutieren und Probleme unter "issues" behandeln....

**Comment by Wolfgang-03** [comment]
Danke für den Hinweis. Ich nehme -dev vcal aus der args raus. 
Diskussionen habe ich freigeschalten.
