### ISSUE TITLE
Status und Programm werden nicht richtig interpretiert

### ISSUE THREAD

**Issue by kl-hobbit** [Wolfgang-03/Open3E-HA#5]
Hallo,

bei mir wurden der Status der Heizkreise und das Betriebsprogramm in HA nicht korrekt angezeigt.

Grund:
Falsches Topic zur Auswertung benutzt:
Z.b. statt open3e/680_1416_MixerTwoCircuitOperationState/Mode muss open3e/680_1415_MixerOneCircuitOperationState/Mode/ID verwendet werden.

Das heisst in vitocal250.yaml müssen die Topics in den folgenden Zeilen durch /ID ergänzt werden:
16
65
618
750

Anlage: IDU Vitocal 250-A AWO-E-AC 251.A16, installiert vor 2 Wochen

**Comment by Wolfgang-03** [comment]
Hallo kl-hobbit, 

vielen Dank für den Hinweis, da wurden wohl die Datenpunkte etwas angepasst. Ich hatte in meinem Live-System noch nicht die aktuelle Version von Open3E laufen, deshalb ist mir das nicht aufgefallen. Ich habe das korrigiert.
