### ISSUE TITLE
Zustand binary_sensor unbekannt

### ISSUE THREAD

**Issue by Stoffelhessen** [Wolfgang-03/Open3E-HA#6]
Bei mir funktionieren die binary_sensor nicht. Hier wird immer der Zustand Unbekannt angegeben.
Ich würde gerne weitere Informationen liefern, nur leider wieß ich nicht was gebraucht wird.
Bei einer Manuelle Abfrage bekomme ich z.B. für den Zustand des Kopressors diese Infos auf der CLI, in diesem Fall läuft der Kopressor ("PowerState": 1) läuft der Kompressor nicht steht in diesem Feld ("PowerState": 0)

`open3e -c can0 -dev vcal -r 2351 -v`
`vcal 2351 HeatPumpCompressor {"PowerState": 1, "ErrorState": 0}`
`closing 0x680 - bye!`

**Comment by Wolfgang-03** [comment]
Hallo Stoffelhessen, 

ich würde vermuten Du hast eine neuere Firmware auf deiner Vitocal als ich auf meiner. Bei mir liefert der DID 2351 nur 

`2351 HeatPumpCompressor 0.0`

Ich denke wenn Du das MQTT-Topic in der vitocal250.yaml entsprechend anpasst, also statt

`state_topic: "open3e/680_2351_HeatPumpCompressor"`

verwende 

`state_topic: "open3e/680_2351_HeatPumpCompressor/PowerState"`

dann sollte das bei Dir funktionieren.

**Comment by Stoffelhessen** [comment]
Hallo Wolfgang,
dein Ansatz war gut, aber noch nicht ganz vollständig.
Die Werte für payload_off und Payload_on mussten auch noch geändert werden, von "0.0" in "0" bzw. "1.0" in "1" . 
Nun funktioniert es aber.
Ich habe hierdurch sehr viel gelernt, wie die yaml-Datei aufgebaut ist.
Vielen Dank für deine Unterstützung. 

Meine Vitocal 250-A hat den Softwarestand 2323

Original Auszug aus der "vitocal250.yaml"
    # Vitocal 250 - Kompressor
    - name: "Vitocal Kompressor Status"
      state_topic: "open3e/680_2351_HeatPumpCompressor"
      unique_id: 680_2351_HeatPumpCompressor
      object_id: 2351_heatpumpcompressor
      device:
        name: "Open3e_Vitocal250A"
        identifiers: !secret vitocal_sn
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      payload_off: "0.0"
      payload_on: "1.0"
      icon: mdi:power

Dies ist meine abgeänderte Version
    # Vitocal 250 - Kompressor
    - name: "Vitocal Kompressor Status"
      state_topic: "open3e/680_2351_HeatPumpCompressor/PowerState"
      unique_id: 680_2351_HeatPumpCompressor
      object_id: 2351_heatpumpcompressor
      device:
        name: "Open3e_Vitocal250A"
        identifiers: MeineSN
        manufacturer: "Viessmann"
        model: "Vitocal 250-A"
      payload_off: "0"
      payload_on: "1"
      icon: mdi:power

**Comment by Wolfgang-03** [comment]
Da hast Du natürlich Recht, 

> Die Werte für payload_off und Payload_on mussten auch noch geändert werden, von "0.0" in "0" bzw. "1.0" in "1" .

Viessmann hat offensichtlich von Float auf Integer umgestellt, was eigentlich auch Sinn macht, wenn der Wert sowieso nur 0 oder 1 haben kann.

**Comment by Stoffelhessen** [comment]
Hallo Wolfgang,

ich habe deine Heizugssteuerung für mich etwas umgebaut, um immer nur einen Wert zu schreiben und nicht immer alle 3 Werte im Abstand von 2°C .

`      # Einstellung HK1 Solltemperatur (3 .. 37 Grad)`
`      temperature_state_topic: "open3e/680_1643_MixerOneCircuitCurrentTemperatureSetpoint"`
`      temperature_command_topic: "open3e/cmnd"`
`      temperature_command_template: >`
`        {% set ISTtempComfort = (states('sensor.424_mixeronecircuitroomtemperaturesetpoint_comfort') | int)*10 %}`
`        {% set ISTtempStandard = (states('sensor.424_mixeronecircuitroomtemperaturesetpoint_standard') | int)*10 %}`
`        {% set ISTtempReduced = (states('sensor.424_mixeronecircuitroomtemperaturesetpoint_reduced') | int)*10 %}`
`        {% set value_target = (value*10) | int %}`
`        {% set hk1_bp = states('sensor.1415_mixeronecircuitoperationstate') %}`
`        {% if (hk1_bp=="Komfort") %}`
`        {% set value_com = min(max(30, value_target),370) %}`
`        {% set value_sta = min(max(30, ISTtempStandard),370) %}`
`        {% set value_red = min(max(30, ISTtempReduced),370) %}`
`        {% elif (hk1_bp=="Reduziert") or (hk1_bp=="Frostschutz") or (hk1_bp=="Abschaltbetrieb") %}`
`        {% set value_com = min(max(30, ISTtempComfort),370) %}`
`        {% set value_sta = min(max(30, ISTtempStandard),370) %}`
`        {% set value_red = min(max(30, value_target),370) %}`
`        {% else %}`
`        {% set value_com = min(max(30, ISTtempComfort),370) %}`
`        {% set value_sta = min(max(30, value_target),370) %}`
`        {% set value_red = min(max(30, ISTtempReduced),370) %}`
`        {% endif %}`
`        {% set cmddata = '%02x' % (value_com % 256) + '%02x' % (value_com // 256) + '%02x' % (value_sta % 256) + '%02x' % (value_sta // 256) + '%02x' % (value_red % 256) + '%02x' % (value_red // 256) + '000000' %}`
`        {% set cmd = {'mode': 'write-raw', 'data':[[424, cmddata]]} %}`
`        {{ cmd | to_json }}`

Kurz zur Erklärung, als erstes werden die 3 aktuellen Werte comfort, standard & reduced in jeweils eine Variable geschrieben, als integer und diese mit 10 Multipliziert, diese werte können dann ohne weitere Bearbeitung auch direkt wieder geschrieben werden.
Die Überprüfung der Range 3-37°C habe ich behalten um evtl. Fehler abzufangen. 
Ersetzt habe ich die value_target +/-2 durch die aktuellen Werte.
Evtl. kann dies jemand anderes brauchen.

Lieben Gruß Christopher
